name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests on iOS Simulator
        run: |
          flutter test
          flutter build ios --no-codesign
          xcrun simctl create TestDevice com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-2
          xcrun simctl boot TestDevice
          flutter drive --target=integration-test/app_test.dart -d TestDevice
        env:
          CI: true
